### ISSUE TITLE
Alive Domain Function Detection

### ISSUE THREAD

**Issue by secfb** [bing0o/SubEnum#1]
SubEnum is really well thought out.
It would be nice if httprobe was added to detect live domains. This feature would be great if optional.
-rs=resolve 
```bash
ALIVE(){
cat $domain-*| httprobe -c 40>httprobe_$domain.txt;cat httprobe_$domain.txt|cut -d "/" -f3|sort -u|tee r_$domain.txt
}
```
--------
```powershell
subenum -l domain.txt -u Amass,Subfinder -rs 
```

**Comment by bing0o** [comment]
that's really a good idea, working on it 
thanks @secfb

**Comment by bing0o** [comment]
but i suggest to keep the protocols and don't use cut, to be available for direct use

**Comment by bing0o** [comment]
@secfb the [script](https://github.com/bing0o/SubEnum) is updated, please check it out, and give me your feedback.

**Comment by secfb** [comment]
@bing0o It was really nice. I made some editing in the function.

```powershell
ALIVE(){
	printf "$bold[+] Resolving $end"
	printf "                        \r"
	cat $1 | httprobe -c $thread > "resolved-$2.txt"
	echo -e $green"[+] Resolved(http/https):  $end$(wc -l resolved-$2.txt)"
	cat resolved-$2.txt|cut -d "/" -f3 | sort -u>rs-domain-$2.txt
	echo -e $red"[+] Resolved Uniq Domain:$end $(wc -l rs-domain-$2.txt)"
}
```
```ruby
 bash subenum.sh -d testfire.net -u Findomain,crt -r 
```
<img width="678" alt="1" src="https://user-images.githubusercontent.com/38748801/82107155-24ce2180-972e-11ea-9d8f-f4ea8ef2a9c8.png">

**Comment by bing0o** [comment]
that's actually a good idea, and that's what i do after resolving the subs, but i don't want it to make a lot of output files, especially when when u have a long list of targets 
 thanks for your contribution :)

**Comment by bing0o** [comment]
@all-contributors please add @secfb for code
