### ISSUE TITLE
parallel module missing data

### ISSUE THREAD

**Issue by 0xhunster** [bing0o/SubEnum#14]
Nice update. but when I run parallel script module missing some data. Could you check, please?

**Comment by bing0o** [comment]
hello @0xhunster, can you please tell me which command did you run.

**Comment by 0xhunster** [comment]
./subenum.sh -d hackerone.com
and 
./subenum.sh -d hackerone.com -p

I saw crt.sh missing data when I run parallel.

**Comment by bing0o** [comment]
I just tried the two commands and they gave the same results

![image](https://user-images.githubusercontent.com/25457545/159204509-5d790477-b7b6-4634-a0ce-c62b3ee09698.png)

sometimes it gives 0 results for some reasons (internet issues maybe).

**Comment by 0xhunster** [comment]
But can you see your screenshot, when you use parallel, findomain found 14, and when you run the normal scan findomain found 17. I got some times 0. That's the issue. Could you give me your discord or telegram?

**Comment by bing0o** [comment]
Yep that happens because of the unstable internet connection, and I think even if you run findomain alone multiple times you won't get the same result every time. 
my discord: bing0o#8343

**Comment by bing0o** [comment]
not only findomain, most of the tools doesn't give the same results all the time.

**Comment by 0xhunster** [comment]
request send done :). But one thing if the domains continue to be missed, then a lot will be missed :(

**Comment by bing0o** [comment]
Yep, that's why we need some luck. 
Happy hacking
