### ISSUE TITLE
--output not working 

### ISSUE THREAD

**Issue by Anh3d0ni4** [bing0o/SubEnum#18]
Hi. any time I use `--output ` it stay with default output how can I save the final result into a file?
the command I used `./subenum.sh -l tmp -s  -o tmp2`
![image](https://user-images.githubusercontent.com/75607964/187069605-5e9b1e7f-dc76-4fc8-9e95-f8f4b0beb1aa.png)

**Comment by bing0o** [comment]
Hello @Anh3d0ni4, thank you for letting me know, it seems like there's an issue when using the option `-l/--list`, it will output the default file name.
Working on the fix.

**Comment by bing0o** [comment]
The issue has been fixed!
thanks again.
