### ISSUE TITLE
add

### ISSUE THREAD

**Issue by scottishhunter1** [bing0o/SubEnum#6]
marge this script with yours for more good result 
https://github.com/random-robbie/AutoRecon/blob/master/recon.sh

**Comment by scottishhunter1** [comment]
https://github.com/allyomalley/LiveTargetsFinder and also add this one to for port scans and live target

**Comment by bing0o** [comment]
good idea, but i want to keep subenum only for subdomains enumeration, i'm gonna make another tool and include subenum and those tools on it .

thank you!
