### ISSUE TITLE
Suggestion !

### ISSUE THREAD

**Issue by attacker007** [bing0o/SubEnum#7]
Hi @bing0o 

Thanks for the great tool.. Can you please add this API tool for fetching subdomains?

```
https://developers.facebook.com/tools/ct/search/?query=

```

**Comment by cihanmehmet** [comment]
Hi @attacker007 
I think this is not necessary? You can use Amass or subfinder for Facebook api. I recommend Subfinder. There is already a subfinder in this script. You just need to feed the api source.

```yaml 
subfinder -config config.yaml
```
https://github.com/projectdiscovery/subfinder/blob/master/config.yaml

**Comment by bing0o** [comment]
hello @attacker007 ,
thanks for kind word :), like what @cihanmehmet said, i'm not sure about subfinder, but amass and findomain use facebook API to find subdomains.

thanks for you suggestion .

**Comment by attacker007** [comment]
Hi @bing0o  

Actually I tried all of them and none of'em returning all the subdomains listed on "developers.facebook.com" ...

**Comment by bing0o** [comment]
hi @attacker007 ,
can you give me the exact query that you used to get subdomains from facebook API?.

**Comment by attacker007** [comment]
Hi @bing0o try with any domain like yahoo.com

**Comment by bing0o** [comment]
Thank you @attacker007 for the idea, but facebook API is already being used with findomain, subfinder and amass .

if u have more ideas please feel free to open an Issue/PR or hit me on [Twitter](https://twitter.com/hack1lab)
