### ISSUE TITLE
Multiple Scan(parallel) Suggestion

### ISSUE THREAD

**Issue by cihanmehmet** [bing0o/SubEnum#8]
You really set this tool up. Nice script. Have you ever come across the project underneath? It scans really fast(Except resolve field 😂).
https://github.com/cihanmehmet/sub.sh

It would be nice if it was added to your subenum.
sample use.

### call function
```powershell
export -f wayback && export -f crt && export -f bufferover  && export -f Findomain && export -f Subfinder  && export -f Amass && export -f Assetfinder 
```
### function execution
```yaml
parallel ::: wayback crt bufferover Findomain Subfinder Amass Assetfinder ::: $domain	
```
If you use it in parallel, you should use it as follows as it will delete at the same time.
------
#### Save Subdomain List
```diff
-tmp-wayback-$domain
+tmp-$domain-wayback
```
####  Out function
```diff
-tmp-*
+tmp-$domain*
```
------
It can be run in parallel with the current tool as follows. `wc -l subdomainlist.txt => 10`
```console
parallel -a subdomainlist.txt -j10 'subenum -d {1}'
```

**Comment by bing0o** [comment]
thank you for kind words :)
i took a look at your script [sub.sh](https://github.com/cihanmehmet/sub.sh), and Parallel made it fast and I was thinking about making subenum.sh faster,  your idea is really good , I will do some tests soon, and get back to you.

**Comment by bing0o** [comment]
@cihanmehmet it took a long time, but I finally did it 😄,
if there are any issues, please let me know,
thanks.

**Comment by cihanmehmet** [comment]
In this way, the tool turned out to be really beautiful and useful. With the addition of the parallel command the output really comes faster.
