### ISSUE TITLE
Have to add new source (Rapiddns)

### ISSUE THREAD

**Issue by remonsec** [bing0o/SubEnum#9]
Hello
I was trying to add a new souce on your SubEnum tool 
The source i like to add is [rapiddns](https://rapiddns.io/) I created the function and added the name on array as well but dont know why i stacked and not fetching the function at all.

I am giving you the necessary codes please add this source on your tool for passive enumeration 
Thanks

### Oneliner
```
curl -s "https://rapiddns.io/subdomain/$domain?full=1" | grep -oP '_blank">\K[^<]*' | sort -u
```

### Function that may fit to your tool
```
rapidns() { 
	[ "$silent" == True ] && curl -s "https://rapiddns.io/subdomain/$domain?full=1" | grep -oP '_blank">\K[^<]*' | sort -u | anew subenum-$domain.txt  || {
		printf "$bold[+] Rapidns$end"
		printf "                        \r"
		curl -s "https://rapiddns.io/subdomain/$domain?full=1" | grep -oP '_blank">\K[^<]*' | sort -u > tmp-rapidns-$domain
		echo -e "$bold[*] Rapidns$end: $(wc -l < tmp-rapidns-$domain)"
	}
}
```

**Comment by cihanmehmet** [comment]
there are already amass, findomain, rapiddns in subfinder. I think there is no need.
I think it would be better if this tool was added.
https://github.com/Cgboal/SonarSearch

**Comment by bing0o** [comment]
Hello @remonsec, sorry for taking too long to reply, and thanks for the idea but like @cihanmehmet said it's already used with subfinder and amass, so there's no need .

please if u have other ideas feel free to open an issue or hit me on [Twitter](https://twitter.com/hack1lab)
